name: "Build and release Electron build"

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: ["windows-latest"]

    steps:  
    - name: "Checkout Code"
      uses: actions/checkout@v3

    - name: "Setup Node"
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Build Distribution
      run: npm run build

      #Create Release
    - name: Create Github Release
      id:  create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        prerelease: ${{ contains(github.ref_name, 'pre') }}

    
    - name: Publish Build
      uses: samuelmeuli/action-electron-builder@v1
      with:
        args: --win
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



      
